default:
  cdn_url: "https://cdn.cypress.io"
  desktop_url: "https://download.cypress.io/desktop"
  desktop_manifest_url: https://download.cypress.io/desktop.json
  chromium_url: https://download.cypress.io/chromium
  chromium_manifest_url: https://download.cypress.io/chromium.json

development: &development
  api_url: "https://cypress-local.bsstag.com/"

test:
  <<: *development

staging:
  api_url: "https://cypress-local.bsstag.com/"

production:
  api_url: "https://cypress-local.bsstag.com/"
